spring:
  dubbo:
    application:
      name: yss-service
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.alibaba.dubbo.demo.service